### PR TITLE
Numbers larger than MAX_SAFE_INT (pow(2, 53) - 1) should be represented as string

### PR DESCRIPTION
**Pull request by SoHotSoup**
Due to javascript problems with big ints, big ints (Tweet ID, PAN etc.) should be represented as strings.

### CODE REVIEW

**Comment by badunk** [comment]
Does jquery's `param` accept big ints?

Can you write a test for this?

Thanks

**Comment by SoHotSoup** [comment]
Yes, I have big int (card number) as string on one side, after deperimeterization deparam test it and it is number, but it is too large and it is rounded on wrong value. The same happens if you try to send tweet id in querystring...  Tests are written and none if it fails. Maybe it will be better to test Math.abs of val to escape same problem for negative values, but I think that only identifiers are that large... If you want I can change that?

**Comment by SoHotSoup** [comment]
I've changed max safe int to ((+val + '') === val) that way if, browser cast to number right it would be represented as number.

**Comment by badunk** [comment]
I think I didn't quite understand what you were trying to do.  I took another look at it and it makes sense.

jquery doesn't have this problem because it converts everything to string.

**Pull request merged**
